[build]
  # Enhanced build command with explicit installation of critters
  command = "npm install critters --save && npm install && next build"
  publish = ".next"
  base = "."

# Add redirects to ensure client-side routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Important environment variables for Next.js 15+
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PRIVATE_STANDALONE = "true"
  NEXT_DEBUG_MODE = "false"
  CI = "false" # Prevents warnings from being treated as errors

# Use the latest Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  
# Improve function bundling performance
[functions]
  # Include necessary files and specify included_files list
  node_bundler = "esbuild"
  external_node_modules = ["next"]
  included_files = ["node_modules/critters/**/*"]
