[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

# Tell Netlify where to find the Next.js app
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # Specify that the app is in the src directory
    src_dir = "src"

# Handle client-side routing for static Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
