[build]
  base = "/"
  command = "bun run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

# Handle client-side routing for static Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
