[build]
  # Build command for Next.js on Netlify
  command = "npm install && npm run build"
  publish = ".next"
  base = "."

[build.environment]
  # Allow Netlify to handle Next.js correctly
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

# Use the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
