name: Deploy to Netlify and Windsurf

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'bell-plus-aesthetic/bell-plus-aesthetic/package-lock.json'

      - name: Install dependencies
        run: |
          cd bell-plus-aesthetic/bell-plus-aesthetic
          npm ci

      - name: Build
        run: |
          cd bell-plus-aesthetic/bell-plus-aesthetic
          npm run build

      # Deploy to Netlify using their official action
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=bell-plus-aesthetic/bell-plus-aesthetic/.next --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # Deploy to Windsurf using their CLI
      - name: Install Windsurf CLI
        run: npm install -g @windsurf/cli

      - name: Deploy to Windsurf
        run: |
          cd bell-plus-aesthetic/bell-plus-aesthetic
          windsurf deploy --token ${{ secrets.WINDSURF_TOKEN }} --project-id d8180aef-d9b8-41cd-b4d0-cfbfb7577f1d
        env:
          WINDSURF_TOKEN: ${{ secrets.WINDSURF_TOKEN }}
