name: Deploy to Windsurf

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'bell-plus-aesthetic/bell-plus-aesthetic/package-lock.json'

      - name: Install dependencies
        run: |
          cd bell-plus-aesthetic/bell-plus-aesthetic
          npm ci

      - name: Build
        run: |
          cd bell-plus-aesthetic/bell-plus-aesthetic
          npm run build

      # Direct deployment to Windsurf using curl
      - name: Deploy to Windsurf
        run: |
          cd bell-plus-aesthetic/bell-plus-aesthetic
          # Create a tar of the build directory
          tar -czf build.tar.gz .next
          
          # Upload to Windsurf using their API
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.WINDSURF_TOKEN }}" \
            -F "file=@build.tar.gz" \
            -F "project_id=d8180aef-d9b8-41cd-b4d0-cfbfb7577f1d" \
            https://api.windsurf.build/v1/deployments
        env:
          WINDSURF_TOKEN: ${{ secrets.WINDSURF_TOKEN }}
